name: freelancer_app
description: A new Flutter project for Freelancer App (Phase 1).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  provider: ^6.1.1
  uuid: ^4.3.3
  fl_chart: ^1.1.1
  google_fonts: ^7.0.0
  shimmer: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.0
  confetti: ^0.8.0
  file_picker: ^8.1.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
